name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag onlyoffice-documentserver:latest
    - name: upload tencent cloud
      env:
        tencentlogin: ${{ secrets.TENCENTCLOUDLOGIN }}
        tencentpassword: ${{ secrets.TENCENTCLOUDPASSWORD }}
        tencentdockername: ccr.ccs.tencentyun.com/dailybo/onlyoffice-documentserver
      run:  |
        docker login -u $tencentlogin -p $tencentpassword ccr.ccs.tencentyun.com
        docker tag onlyoffice-documentserver:latest $tencentdockername:$GITHUB_RUN_ID
        docker tag onlyoffice-documentserver:latest $tencentdockername:latest
        docker push $tencentdockername:$GITHUB_RUN_ID
        docker push $tencentdockername:latest
